# ** create configMap to store database url
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
data:
  database-url: mongodb-svc
---

# *** create mongoexpress deployment
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongoexp-dep
  labels:
    app: mongoexp-dep
spec:
  selector:
    matchLabels:
      app: mongoexp-pod
  replicas: 1
  template:
    metadata:
      name: mongoexp-pod
      labels:
        app: mongoexp-pod
    spec:
      containers:
      - name: mongoexp-container
        image: mongo-express
        ports:
        - name: mongoexp-port
          containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              name: mongodb-configmap
              key: database-url
---

# create mogo-express external service
#
apiVersion: v1
kind: Service
metadata:
  name: mongoexp-svc
  labels:
    app: mongoexp-svc
spec:
  selector:
    app: mongoexp-pod
  type: LoadBalancer
  ports:
  - name: web
    protocol: TCP
    port: 8081
    targetPort: mongoexp-port