## ** create nginx ingress service
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: myingress
spec:
  rules:
  - host: "myapps.com"
    http:
      paths:
        backend:
          serviceName: nginx-svc
          servicePort: 80
    